Make the DEV library like other libraries.

diff --git a/src/cpp/lib/dev/Test/script/regression b/src/cpp/lib/dev/Test/script/regression
--- a/src/cpp/lib/dev/Test/script/regression
+++ b/src/cpp/lib/dev/Test/script/regression
@@ -1,7 +1,7 @@
 #!/bin/bash
 ##----------------------------------------------------------------------------
 ##
-##       Copyright (C) 2022 Frank Eskesen.
+##       Copyright (C) 2022-2023 Frank Eskesen.
 ##
 ##       This file is free content, distributed under the MIT license.
 ##       (See accompanying file LICENSE.MIT or the original contained
@@ -16,36 +16,60 @@
 ##       Run regression tests.
 ##
 ## Last change date-
-##       2022/10/27
+##       2023/01/14
 ##
 ##############################################################################
 
-set -x
+##############################################################################
+## Insure that the library is up to date
+pushd ../. >/dev/null
+echo ""
+pwd
 make
+rc=$?
+popd >/dev/null
+[[ $rc != 0 ]] && { echo "Library build failed"; exit 1; }
 
-T_Option
-[[ $? != 0 ]] && { echo "Test failed"; exit 1; }
-sleep 5
+##############################################################################
+## Insure that test executables are up to date
+echo ""
+pwd
+make
+[[ $? != 0 ]] && { echo "Test build failed"; exit 1; }
 
-T_Quick --verbose
-[[ $? != 0 ]] && { echo "Test failed"; exit 1; }
-sleep 5
-
-TestIoda
-[[ $? != 0 ]] && { echo "Test failed"; exit 1; }
-sleep 5
-
+##############################################################################
+## Run the tests
+echo ""
+echo "T_Stream --server --client --verbose **********************************"
 T_Stream --server --client --verbose
 [[ $? != 0 ]] && { echo "Test failed"; exit 1; }
-sleep 5
 
-T_Stream --server --stream --verbose
+echo ""
+echo T_Stream --server --stress --verbose "**********************************"
+T_Stream --server --stress --verbose
 [[ $? != 0 ]] && { echo "Test failed"; exit 1; }
-sleep 5
 
-T_Stream --server --stream=1 --verbose
+echo ""
+echo "T_Stream --server --stress=1 --verbose ********************************"
+T_Stream --server --stress=1 --verbose
 [[ $? != 0 ]] && { echo "Test failed"; exit 1; }
-sleep 5
 
-T_Stream --server --stream=10 --verbose
+echo ""
+echo "T_Stream --server --stress=10 --verbose *******************************"
+T_Stream --server --stress=10 --verbose
+[[ $? != 0 ]] && { echo "Test failed"; exit 1; }
+
+echo ""
+echo "T_Option **************************************************************"
+T_Option
+[[ $? != 0 ]] && { echo "Test failed"; exit 1; }
+
+echo ""
+echo "T_Quick --verbose *****************************************************"
+T_Quick --verbose
+[[ $? != 0 ]] && { echo "Test failed"; exit 1; }
+
+echo ""
+echo "TestIoda **************************************************************"
+TestIoda
 [[ $? != 0 ]] && { echo "Test failed"; exit 1; }
