Batch files using bash features need bash invocations.

diff --git a/bat/connect b/bat/connect
--- a/bat/connect
+++ b/bat/connect
@@ -1,7 +1,7 @@
 #!/bin/bash
 ##----------------------------------------------------------------------------
 ##
-##       Copyright (C) 2018-2019 Frank Eskesen.
+##       Copyright (C) 2018-2024 Frank Eskesen.
 ##
 ##       This file is free content, distributed under the MIT license.
 ##       (See accompanying file LICENSE.MIT or the original contained
@@ -16,15 +16,15 @@
 ##       Connect to a SCREEN
 ##
 ## Last change date-
-##       2019/10/07
+##       2024/01/04
 ##
 ## Usage-
 ##       connect gridname
 ##
 ##############################################################################
-if [[ -z "$1" ]] ; then echo "Missing SCREEN name"; exit 1; fi
+if [[ -z "$@" ]] ; then echo "Missing SCREEN name"; exit 1; fi
 
-LIST=`ps -fu $LOGNAME| grep SCREEN| grep -v grep| grep $1| awk '{print $2}'`
+LIST=`ps -fu $LOGNAME| grep SCREEN| grep -v grep| grep "$@"| awk '{print $2}'`
 if [[ -z "$LIST" ]] ; then echo "Invalid SCREEN name"; exit 1; fi
 for i in $LIST
 do
