detar and mktar gzip by default.

diff --git a/bat/detar b/bat/detar
--- a/bat/detar
+++ b/bat/detar
@@ -1,7 +1,7 @@
 #!/bin/bash
 ##----------------------------------------------------------------------------
 ##
-##       Copyright (C) 2016-2019 Frank Eskesen.
+##       Copyright (C) 2016-2023 Frank Eskesen.
 ##
 ##       This file is free content, distributed under the MIT license.
 ##       (See accompanying file LICENSE.MIT or the original contained
@@ -13,14 +13,82 @@
 ##       detar
 ##
 ## Purpose-
-##       Extract a tar file.
+##       Extract a gzipped tar file.
 ##
 ## Last change date-
-##       2019/10/08
+##       2023/06/06
 ##
 ## Usage-
-##       detar filename
+##       detar {-v} filename
 ##
 ##############################################################################
-tar -xvf $1.tar
+
+##############################################################################
+## Extract switch names
+sparm=""
+
+for i in $*
+do
+  case $i in
+    -c)
+      echo "Invalid switch $i"
+      heading $0
+      exit 1
+      ;;
+
+    -f)
+      echo "Specify the input filename as the only positional parameter"
+      heading $0
+      exit 1
+      ;;
+
+    -*)
+      sparm="$sparm $i"
+      shift
+      ;;
+
+    *)
+      break
+      ;;
+
+  esac
+done
+
+##############################################################################
+## Extract parameters
+if [ "" = "$1" ] ; then
+  echo "Missing input tar_file(.tgz) name"
+  heading $0
+  exit
+fi
+tar_name=$1
+shift
+
+if [ "" != "$1" ] ; then
+  echo "Too many parameters"
+  heading $0
+  exit
+fi
+
+##############################################################################
+## Verify parameters
+if [ ! -f "$tar_name.tgz" ] ; then
+  echo "'$tar_name.tgz' not found."
+  exit
+fi
+
+if [ -e "$tar_name" ] ; then
+  echo "'$tar_name' already exists. It's the output directory name."
+  echo "Delete it and try again."
+  exit
+fi
+
+##############################################################################
+## Extract the tgz file
+cmd="tar $sparm -xzf $tar_name.tgz"
+echo $cmd
+$cmd
+rc=$?
+[[ $rc != 0 ]] && echo "tar command failed, exit code $rc"
+exit $rc
 
diff --git a/bat/mktar b/bat/mktar
--- a/bat/mktar
+++ b/bat/mktar
@@ -1,7 +1,7 @@
 #!/bin/bash
 ##----------------------------------------------------------------------------
 ##
-##       Copyright (C) 2010-2019 Frank Eskesen.
+##       Copyright (C) 2010-2023 Frank Eskesen.
 ##
 ##       This file is free content, distributed under the MIT license.
 ##       (See accompanying file LICENSE.MIT or the original contained
@@ -13,14 +13,83 @@
 ##       mktar
 ##
 ## Purpose-
-##       Create a tar file.
+##       Create a gzipped tar file.
 ##
 ## Last change date-
-##       2019/10/08
+##       2023/06/06
 ##
 ## Usage-
-##       mktar outfile inppath
+##       mktar {-v} pathname
+##         (Creates pathname.tgz from subdirectory pathname)
 ##
 ##############################################################################
-tar -cvf $1.tar -C $2 .
 
+##############################################################################
+## Extract switch names
+sparm=""
+
+for i in $*
+do
+  case $i in
+    -f)
+      echo "Specify the output filename as the first positional parameter"
+      heading $0
+      exit 1
+      ;;
+
+    -x)
+      echo "Invalid switch $i"
+      heading $0
+      exit 1
+      ;;
+
+    -*)
+      sparm="$sparm $i"
+      shift
+      ;;
+
+    *)
+      break
+      ;;
+
+  esac
+done
+
+##############################################################################
+## Extract parameters
+if [ "" = "$1" ] ; then
+  echo "Missing path name"
+  heading $0
+  exit
+fi
+tar_name=$1
+shift
+
+if [ "" != "$1" ] ; then
+  echo "Too many parameters"
+  heading $0
+  exit
+fi
+
+##############################################################################
+## Verify parameters
+if [ ! -d "$tar_name" ] ; then
+  echo "'$tar_name' is not a directory."
+  echo "Use a real directory name."
+  exit
+fi
+
+if [ -e "$tar_name.tgz" ] ; then
+  echo "'$tar_name.tgz' already exists."
+  echo "Delete it and try again."
+  exit
+fi
+
+##############################################################################
+## Create the tgz file
+cmd="tar $sparm -czf $tar_name.tgz $tar_name"
+echo $cmd
+$cmd
+rc=$?
+[[ $rc != 0 ]] && echo "tar command failed, exit code $rc"
+exit $rc
