Script changes allow encryption specifying a specific key.

diff --git a/bat/editgpg b/bat/editgpg
--- a/bat/editgpg
+++ b/bat/editgpg
@@ -1,7 +1,7 @@
 #!/bin/bash
 ##----------------------------------------------------------------------------
 ##
-##       Copyright (C) 2010-2024 Frank Eskesen.
+##       Copyright (C) 2010-2025 Frank Eskesen.
 ##
 ##       This file is free content, distributed under the MIT license.
 ##       (See accompanying file LICENSE.MIT or the original contained
@@ -16,10 +16,29 @@
 ##       Edit a GPG encrypted file.
 ##
 ## Last change date-
-##       2024/08/20
+##       2025/04/13
 ##
 ## Usage-
-##       editgpg [-as userid] filename
+##       editgpg [-as user] filename
+##
+## Implementation notes-
+##       GPG configuration information is kept in ~/.gnupg/.
+##       Using information in filename.gpg, GPG automatically selects the
+##       decryption key.
+##
+##       There is no default encryption key.
+##       - Use the default configuration file, ~/.gnupg/gpg.conf to define the
+##         default encryption key.
+##       - This default encryption key *MUST* be in the secret key list.
+##       IF YOU ENCODE WITH AN ENCRYPTION KEY YOU CANNOT DECODE, YOUR DATA
+##       WILL BE IRRETRIEVABLY LOST.
+##
+##       "gpg --list-keys" displays your key ring.
+##       "gpg --list-secret-keys" displays your secret key ring.
+##
+## See also:
+##       GPG user's guide:  https://www.gnupg.org/documentation/guides.html
+##       GPG user's manual: https://www.gnupg.org/documentation/manuals.html
 ##
 ##############################################################################
 
@@ -28,51 +47,72 @@
 function usage
 {
   echo ""
-  echo "$0: Edit a GPG encrypted file"
-  echo "Usage: $0 [-as username] file"
-  echo "Filename file.gpg must exist"
-  echo "The GPG encrypted file is decrypted into \"file\", and this"
-  echo "unencrypted file is edited. If \"file\" exists when the editor"
-  echo "exits, the file is reencrypted into \"file.gpg\""
+  echo "$0: Edit a file encrypted by GPG."
+  echo "Usage: $0 filename"
+  echo "File \"filename.gpg\" must exist; \"filename\" should not."
+  echo "The GPG encrypted file is decrypted into \"filename\", "
+  echo "then this unencrypted file is edited."
+  echo "If \"filename\" still exists when the editor exits, the file is"
+  echo "the file is reencrypted and replaces \"filename.gpg\" "
+
+  echo ""
+  echo "The information in \"filename.gpg\" allows GPG to automatically"
+  echo "select the decryption key."
+
+  echo ""
+  echo "GPG configuration information is kept in ~/.gnupg/gpg.conf"
+  echo "There is no default encryption key."
+  echo "- Use the default configuration file, ~/.gnupg/gpg.conf to define the"
+  echo "  default encryption key."
+  echo " -This default encryption key *MUST* be in your secret key list."
+
+  echo ""
+  echo "  ** WARNING**"
+  echo "    IF YOU CANNOT DECODE THE ENCRYPTION KEY, YOUR DATA WILL BE LOST."
+  echo "    IT'S IRRETRIEVABLY LOST; THE ORIGINAL FILE IS *DELETED*"
 }
 
 ##############################################################################
 ## Parameter check
-GPGUSER=$USER
+if [[ "$1" = "-help" || "$1" = "--help" ]] ; then
+  usage
+  exit 1
+fi
+
 GPGFILE=$1
-if [ "$GPGFILE" = "-as" ] ; then
+if [[ -z "$GPGFILE" ]] ; then
+  echo "ERROR: Filename not specified"
+  usage
+  exit 1
+fi
+
+if [[ ! -z "$2" ]] ; then
   shift
-  GPGUSER=$1
-  shift
-  GPGFILE=$1
-  if [ -z "$GPGUSER" ] ; then
-    echo "Error: username not specified"
-    usage
-    exit 1
+  echo "ERROR: Extra parameters: $@"
+  usage
+  exit 1
+fi
+
+if [[ ! -f "$GPGFILE.gpg" ]] ; then
+  echo "ERROR: File \"$GPGFILE.gpg\" does not exist"
+  if [[ -f "$GPGFILE" ]] ; then
+    echo "(Since \"$GPGFILE\" exists, consider using \"intogpg $GPGFILE\")"
   fi
-fi
-
-if [ -z "$GPGFILE" ] ; then
-  echo "Error: filename not specified"
   usage
   exit 1
 fi
 
-if [ ! -z "$2" ] ; then
-  echo "Error: Extra parameter(s)"
+if [[ -f "$GPGFILE.gpg~" ]] ; then
+  echo "ERROR: File \"$GPGFILE.gpg~\" exists"
+  echo "(This file temporarily saves \"$GPGFILE.gpg\". Maybe \"$GPGFILE.gpg\" can't be decrypted.)"
   usage
   exit 1
 fi
 
-if [ ! -f "$GPGFILE.gpg" ] ; then
-  echo "Error: file \"$GPGFILE.gpg\" does not exist"
-  usage
-  exit 1
-fi
-
-if [ -f "$GPGFILE" ] ; then
-  echo "Error: file \"$GPGFILE\" exists, but should not."
-  echo "(It may be left over from an earlier error.)"
+if [[ -f "$GPGFILE" ]] ; then
+  echo "ERROR: File \"$GPGFILE\" exists, but should not."
+  echo "(It may be left over from some earlier error.)"
+  echo "(Since \"$GPGFILE.gpg\" exists, you might use \"remove $GPGFILE\")"
   exit 1
 fi
 
@@ -88,10 +128,10 @@ fi
 
 ##############################################################################
 ## Decrypt
-gpg --output $GPGFILE --decrypt $GPGFILE.gpg
+gpg --output $GPGFILE --decrypt $GPGFILE.gpg 2>/dev/null
 rc=$?
-if [ $rc != 0 ] ; then
-  echo "Error: Decryption failure."
+if [[ $rc != 0 ]] ; then
+  echo "ERROR: Decryption failure."
   echo "No file changed."
   exit 1
 fi
@@ -99,7 +139,7 @@ fi
 ##############################################################################
 ## Edit, check resultant
 $EDITOR $GPGFILE
-if [ ! -f "$GPGFILE" ] ; then
+if [[ ! -f "$GPGFILE" ]] ; then
   echo "File \"$GPGFILE\" deleted. No change will occur."
   exit 0
 fi
@@ -107,16 +147,16 @@ fi
 ##############################################################################
 ## Encrypt
 rm $GPGFILE.gpg
-gpg --recipient $GPGUSER --encrypt $GPGFILE
+gpg --encrypt $GPGFILE
 rc=$?
-if [ $rc != 0 ] ; then
+if [[ $rc != 0 ]] ; then
   echo ""
-  echo "gpg --recipient $GPGUSER --encrypt $GPGFILE"
-  echo "Error: Encryption failure."
-  echo "EMERGENCY ACTION REQUIRED."
-  echo "File \"$GPGFILE\" exists but \"$GPGFILE.gpg\" does not."
+  echo "gpg $GPGUSER --encrypt $GPGFILE"
+  echo "ERROR: Encryption failure $rc."
+  echo "File \"$GPGFILE\" still exists; \"$GPGFILE.gpg\" might not be valid."
+  echo "Consider using \"intogpg $GPGUSER $GPGFILE\" to retry encrypting."
   exit 2
 fi
-remove $GPGFILE
 
+remove $GPGFILE
 exit 0
diff --git a/bat/fromgpg b/bat/fromgpg
--- a/bat/fromgpg
+++ b/bat/fromgpg
@@ -19,7 +19,18 @@
 ##       2019/11/26
 ##
 ## Usage-
-##       fromgpg foo
+##       fromgpg filename
+##
+## Implementation notes-
+##       GPG configuration information is kept in ~/.gnupg/.
+##       Using information in filename.gpg, GPG automatically selects the
+##       decryption key.
+##
+##       "gpg --list-keys" displays your key ring.
+##
+## See also:
+##       GPG user's guide:  https://www.gnupg.org/documentation/guides.html
+##       GPG user's manual: https://www.gnupg.org/documentation/manuals.html
 ##
 ##############################################################################
 
@@ -28,48 +39,67 @@
 function usage
 {
   echo ""
-  echo "$0: Decrypt a GPG encrypted file."
-  echo "Usage: $0 file"
-  echo "Filename file.gpg must exist, file must not."
-  echo "File \"file.gpg\" is decrypted into \"file\", then erased."
+  echo "$0: Decrypt a file encrypted by GPG."
+  echo "Usage: $0 filename"
+  echo "File \"filename.gpg\" must exist, \"filename\" should not."
+  echo "The GPG encrypted \"filename.gpg\" is decrypted into \"filename\","
+  echo "then \"filename.gpg\" is then erased."
+
+  echo ""
+  echo "The information in \"filename.gpg\" allows GPG to automatically"
+  echo "select the decryption key."
 }
 
 ##############################################################################
 ## Parameter check
+if [[ "$1" = "-help" || "$1" = "--help" ]] ; then
+  usage
+  exit 1
+fi
+
 GPGFILE=$1
-if [ -z "$GPGFILE" ] ; then
-  echo "Error: filename not specified"
+if [[ -z "$GPGFILE" ]] ; then
+  echo "ERROR: Filename not specified"
   usage
   exit 1
 fi
 
-if [ ! -z "$2" ] ; then
-  echo "Error: Extra parameter(s)"
+if [[ ! -z "$2" ]] ; then
+  shift
+  echo "ERROR: Extra parameters: $@"
   usage
   exit 1
 fi
 
-if [ ! -f "$GPGFILE.gpg" ] ; then
-  echo "Error: file \"$GPGFILE.gpg\" does not exists"
+if [[ ! -f "$GPGFILE.gpg" ]] ; then
+  echo "ERROR: File \"$GPGFILE.gpg\" does not exists"
+  if [[ -f "$GPGFILE" ]] ; then
+    echo "(Since \"$GPGFILE\" exists, consider using \"intogpg $GPGFILE\")"
+  fi
   usage
   exit 1
 fi
 
-if [ -f "$GPGFILE" ] ; then
-  echo "Error: file \"$GPGFILE\" already exists."
+if [[ -f "$GPGFILE" ]] ; then
+  echo "ERROR: File \"$GPGFILE\" exists, but should not."
+  echo "(It may be left over from some earlier error.)"
+  echo "(Since \"$GPGFILE.gpg\" exists, you can use \"remove $GPGFILE\")"
   exit 1
 fi
 
 ##############################################################################
-## Encrypt
-gpg --output $GPGFILE --decrypt $GPGFILE.gpg
+## Decrypt
+gpg --output $GPGFILE --decrypt $GPGFILE.gpg 2>/dev/null
 rc=$?
-if [ $rc != 0 ] ; then
+if [[ $rc != 0 ]] ; then
   rm $GPGFILE 2>/dev/null
-  echo "Error: Decryption failure."
+  echo "ERROR: Decryption failure $rc."
   echo "No file changed."
   exit 1
 fi
 
+##############################################################################
+## Discard the original encrypted file
 rm $GPGFILE.gpg
+
 exit 0
diff --git a/bat/intogpg b/bat/intogpg
--- a/bat/intogpg
+++ b/bat/intogpg
@@ -1,7 +1,7 @@
 #!/bin/bash
 ##----------------------------------------------------------------------------
 ##
-##       Copyright (C) 2010-2019 Frank Eskesen.
+##       Copyright (C) 2010-2025 Frank Eskesen.
 ##
 ##       This file is free content, distributed under the MIT license.
 ##       (See accompanying file LICENSE.MIT or the original contained
@@ -16,10 +16,30 @@
 ##       Encrypt a file using GPG encryption.
 ##
 ## Last change date-
-##       2019/10/08
+##       2025/04/13
 ##
 ## Usage-
-##       intogpg [-as userid] foo
+##       intogpg [-as user] filename
+##
+## Implementation notes-
+##       GPG configuration information is kept in ~/.gnupg/.
+##
+##       There is no default encryption key.
+##       - Use the default configuration file, ~/.gnupg/gpg.conf to define the
+##         default encryption key.
+##       - Use the "-as user" option to set or override the default
+##         encryption key.
+##       - If the "-as user" option isn't set and ~/.gnupg/gpg.conf doesn't
+##         define a default encryption key, you will be prompted for a user
+##         in your key ring to be used for encryption.
+##       IF YOU ENCODE WITH AN ENCRYPTION KEY YOU CANNOT DECODE, YOUR DATA
+##       WILL BE IRRETRIEVABLY LOST.
+##
+##       "gpg --list-keys" displays your key ring.
+##
+## See also:
+##       GPG user's guide:  https://www.gnupg.org/documentation/guides.html
+##       GPG user's manual: https://www.gnupg.org/documentation/manuals.html
 ##
 ##############################################################################
 
@@ -28,61 +48,98 @@
 function usage
 {
   echo ""
-  echo "$0: Encrypt a file using GPG encryption."
-  echo "Usage: $0 [-as username] file"
-  echo "Filename file must exist, file.gpg must not."
-  echo "File \"file\" is encrypted into \"file.gpg\", then erased."
+  echo "$0: Use GPG to Encrypt a file."
+  echo "Usage: $0 [-as user] filename"
+  echo "File \"filename\" must exist, \"filename.gpg\" must not."
+  echo "File \"filename\" is encrypted into \"filename.gpg\", then erased."
+
+  echo ""
+  echo "GPG configuration information is kept in ~/.gnupg/gpg.conf"
+  echo "There is no default encryption key."
+  echo "- Use the default configuration file, ~/.gnupg/gpg.conf to define the"
+  echo "  default encryption key."
+  echo "- Use the \"-as user\" option to set or override the default"
+  echo "  encryption key."
+  echo "- If the \"-as user\" option isn't set and ~/.gnupg/gpg.conf doesn't"
+  echo "  define a default encryption key, you will be prompted for a user"
+  echo "  in your key ring to be used for encryption."
+
+  echo ""
+  echo "  ** WARNING**"
+  echo "    IF YOU CANNOT DECODE THE ENCRYPTION KEY, YOUR DATA WILL BE LOST."
+  echo "    NOT ONLY LOST, IRRETRIEVABLY LOST; THE ORIGINAL FILE IS *DELETED*"
 }
 
 ##############################################################################
 ## Parameter check
-GPGUSER=$USER
+if [[ "$1" = "-help" || "$1" = "--help" ]] ; then
+  usage
+  exit 1
+fi
+
 GPGFILE=$1
-if [ "$GPGFILE" = "-as" ] ; then
+if [[ "$GPGFILE" = "-as" ]] ; then
   shift
   GPGUSER=$1
-  shift
-  GPGFILE=$1
-  if [ -z "$GPGUSER" ] ; then
-    echo "Error: username not specified"
+  if [[ -z "$GPGUSER" ]] ; then
+    echo "ERROR: -as Required parameter 'username' not specified"
     usage
     exit 1
   fi
+
+  shift
+  GPGFILE=$1
 fi
 
-if [ -z "$GPGFILE" ] ; then
-  echo "Error: filename not specified"
+if [[ -z "$GPGFILE" ]] ; then
+  echo "ERROR: Filename not specified"
   usage
   exit 1
 fi
 
-if [ ! -z "$2" ] ; then
-  echo "Error: Extra parameter(s)"
+if [[ ! -z "$2" ]] ; then
+  shift
+  echo "ERROR: Extra parameters: $@"
   usage
   exit 1
 fi
 
-if [ -f "$GPGFILE.gpg" ] ; then
-  echo "Error: file \"$GPGFILE.gpg\" already exists"
+if [[ -f "$GPGFILE.gpg" ]] ; then
+  echo "ERROR: File \"$GPGFILE.gpg\" already exists. Fix this problem."
+  if [[ -f "$GPGFILE" ]] ; then
+    echo "Note: File \"$GPGFILE\" also exists."
+  else
+    echo "Note: File \"$GPGFILE\" DOES NOT exist."
+  fi
   usage
   exit 1
 fi
 
-if [ ! -f "$GPGFILE" ] ; then
-  echo "Error: file \"$GPGFILE\" does not exist."
+if [[ ! -f "$GPGFILE" ]] ; then
+  echo "ERROR: File \"$GPGFILE\" does not exist."
+  usage
   exit 1
 fi
+
+[[ -n "$GPGUSER" ]] && GPGUSER="--recipient $GPGUSER"
 
 ##############################################################################
 ## Encrypt
-gpg --recipient $GPGUSER --output $GPGFILE.gpg --encrypt $GPGFILE
+gpg $GPGUSER --encrypt $GPGFILE
 rc=$?
-if [ $rc != 0 ] ; then
+if [[ $rc != 0 ]] ; then
   rm $GPGFILE.gpg 2>/dev/null
-  echo "Error: Encryption failure."
-  echo "No file changed."
-  exit 1
+  echo ""
+  echo "gpg $GPGUSER --encrypt $GPGFILE"
+  echo "ERROR: Encryption failure $rc."
+  echo "File $GPGFILE unchanged. File $GPGFILE.gpg removed (if created.)"
+  echo "(Do you have permission to write into this subdirectory?)"
+  exit 2
 fi
 
-remove $GPGFILE
+if [[ -n "$GPGUSER" ]] ; then
+  echo "Parameter -as specified, File '$GPGFILE' kept."
+else
+  remove $GPGFILE
+fi
 exit 0
diff --git a/bat/viewgpg b/bat/viewgpg
--- a/bat/viewgpg
+++ b/bat/viewgpg
@@ -1,7 +1,7 @@
 #!/bin/bash
 ##----------------------------------------------------------------------------
 ##
-##       Copyright (C) 2010-2024 Frank Eskesen.
+##       Copyright (C) 2010-2025 Frank Eskesen.
 ##
 ##       This file is free content, distributed under the MIT license.
 ##       (See accompanying file LICENSE.MIT or the original contained
@@ -16,10 +16,21 @@
 ##       View a GPG encrypted file.
 ##
 ## Last change date-
-##       2024/08/20
+##       2024/04/13
 ##
 ## Usage-
-##       viewgpg [-as userid] filename
+##       viewgpg [-as user] filename
+##
+## Implementation notes-
+##       GPG configuration information is kept in ~/.gnupg/.
+##       Using information in filename.gpg, GPG automatically selects the
+##       decryption key.
+##
+##       "gpg --list-keys" displays your key ring.
+##
+## See also:
+##       GPG user's guide:  https://www.gnupg.org/documentation/guides.html
+##       GPG user's manual: https://www.gnupg.org/documentation/manuals.html
 ##
 ##############################################################################
 
@@ -28,38 +39,55 @@
 function usage
 {
   echo ""
-  echo "$0: View a GPG encrypted file"
-  echo "Usage: $0 file"
-  echo "Filename file.gpg must exist"
-  echo "The GPG encrypted file is decrypted into \"file\", and this"
-  echo "unencrypted file is edited. The unencrypted file is deleted"
-  echo "when the editor exits."
+  echo "$0: View a file encrypted by GPG."
+  echo "Usage: $0 filename"
+  echo "File \"filename.gpg\" must exist; \"filename\" should not."
+  echo "The GPG encrypted \"filename.gpg\" is decrypted into \"filename\","
+  echo "then edited."
+  echo "Once the editor exits, the decrypted \"filename\" is deleted."
+
+  echo ""
+  echo "The information in \"filename.gpg\" allows GPG to automatically"
+  echo "select the decryption key."
+
+  echo ""
+  echo "The encrypted file, \"filename.gpg\", is never modified."
 }
 
 ##############################################################################
 ## Parameter check
+if [[ "$1" = "-help" || "$1" = "--help" ]] ; then
+  usage
+  exit 1
+fi
+
 GPGFILE=$1
-if [ -z "$GPGFILE" ] ; then
-  echo "Error: filename not specified"
+if [[ -z "$GPGFILE" ]] ; then
+  echo "ERROR: Filename not specified"
   usage
   exit 1
 fi
 
-if [ ! -z "$2" ] ; then
-  echo "Error: Extra parameter(s)"
+if [[ ! -z "$2" ]] ; then
+  shift
+  echo "ERROR: Extra parameters: $@"
   usage
   exit 1
 fi
 
-if [ ! -f "$GPGFILE.gpg" ] ; then
-  echo "Error: file \"$GPGFILE.gpg\" does not exist"
+if [[ ! -f "$GPGFILE.gpg" ]] ; then
+  echo "ERROR: File \"$GPGFILE.gpg\" does not exist"
+  if [[ -f "$GPGFILE" ]] ; then
+    echo "(Since \"$GPGFILE\" exists, consider using \"intogpg $GPGFILE\")"
+  fi
   usage
   exit 1
 fi
 
-if [ -f "$GPGFILE" ] ; then
-  echo "Error: file \"$GPGFILE\" exists, but should not."
-  echo "(It may be left over from an earlier error.)"
+if [[ -f "$GPGFILE" ]] ; then
+  echo "ERROR: File \"$GPGFILE\" exists, but should not."
+  echo "(It may be left over from some earlier error.)"
+  echo "(Since \"$GPGFILE.gpg\" exists, you can use \"remove $GPGFILE\")"
   exit 1
 fi
 
@@ -75,16 +103,17 @@ fi
 
 ##############################################################################
 ## Decrypt
-gpg --output $GPGFILE --decrypt $GPGFILE.gpg
+gpg --output $GPGFILE --decrypt $GPGFILE.gpg 2>/dev/null
 rc=$?
-if [ $rc != 0 ] ; then
-  echo "Error: Decryption failure."
+if [[ $rc != 0 ]] ; then
+  rm $GPGFILE 2>/dev/null
+  echo "ERROR: Decryption failure $rc."
   echo "No file changed."
   exit 1
 fi
 
 ##############################################################################
-## Decrypt
+## Edit; discard decrypted file
 $EDITOR $GPGFILE
 remove $GPGFILE 2>/dev/null
 
