Fixes issue #2, but dispatch::Task::~Task may have other problems.
Synchronization commit containing lots of temporary debugging code.

diff --git a/src/cpp/lib/pub/Test/script/regression b/src/cpp/lib/pub/Test/script/regression
--- a/src/cpp/lib/pub/Test/script/regression
+++ b/src/cpp/lib/pub/Test/script/regression
@@ -1,7 +1,7 @@
 #!/bin/bash
 ##----------------------------------------------------------------------------
 ##
-##       Copyright (C) 2022 Frank Eskesen.
+##       Copyright (C) 2022-2023 Frank Eskesen.
 ##
 ##       This file is free content, distributed under the MIT license.
 ##       (See accompanying file LICENSE.MIT or the original contained
@@ -16,7 +16,7 @@
 ##       Regression tests
 ##
 ## Last change date-
-##       2022/04/25
+##       2023/05/19
 ##
 ## Implementation notes-
 ##       Run this script from ~/src/cpp/obj/pub/Test, the test subdirectory.
@@ -65,6 +65,17 @@ test_set="$@"
 if [ "$1" == "" ] ; then
   test_set=`ls $DDIR`
 fi
+
+##############################################################################
+## Make sure the prerequisite files are present
+if [[ ! -x $DDIR/_prereq.sh ]] ; then
+  echo "Missing file: $DDIR/_prereq.sh"
+  exit 1
+fi
+
+$DDIR/_prereq.sh
+rc=$?
+[[ $rc != 0 ]] && exit $rc
 
 ##############################################################################
 ## Make sure the test library is up to date
