Added "make install" function. (Installs in ~/bin)

diff --git a/src/cpp/Tools/Makeproj/make b/src/cpp/Tools/Makeproj/make
--- a/src/cpp/Tools/Makeproj/make
+++ b/src/cpp/Tools/Makeproj/make
@@ -1,14 +1,14 @@
 #!/bin/bash
-##############################################################################
+##----------------------------------------------------------------------------
 ##
-##       Copyright (c) 2006-2020 Frank Eskesen.
+##       Copyright (c) 2006-2021 Frank Eskesen.
 ##
 ##       This file is free content, distributed under the "un-license,"
 ##       explicitly released into the Public Domain.
 ##       (See accompanying file LICENSE.UNLICENSE or the original
 ##       contained within http://unlicense.org)
 ##
-##############################################################################
+##----------------------------------------------------------------------------
 ##
 ## Title-
 ##       make
@@ -17,7 +17,7 @@
 ##       Local alias for make
 ##
 ## Last change date-
-##       2020/10/07
+##       2021/07/09
 ##
 ## Usage-
 ##       ./make
@@ -25,9 +25,33 @@
 ## Notes-
 ##       fileformat=unix
 ##
-########
+##############################################################################
 
-########################################################################
+##############################################################################
 # Build the file
-g++ -o makeproj -D_OS_BSD -I~/src/cpp/inc -Wall -Wextra Makeproj.cpp
+g++ -o makeproj -O3 -D_OS_BSD -I~/src/cpp/inc -Wall -Wextra Makeproj.cpp
+
+##############################################################################
+# Test the result
+rc=$?
+if [[ $rc != 0 ]] ; then
+  echo "Compile failed code $rc"
+  exit $rc
+fi
+
+##############################################################################
+# Handle install option
+if [[ "$1" == "install" ]] ; then
+  [[ -d ~/bin ]] || { echo "creating ~/bin"; mkdir ~/bin; }
+  strip makeproj
+  mv -i makeproj ~/bin/.
+  exit 0
+fi
+
+##############################################################################
+# Handle pristine option
+if [[ "$1" == "pristine" ]] ; then
+  rm -f makeproj
+  exit 0
+fi
 
